agent_id: pipeline_v1
agent_type: sales_pipeline
name: "Sales Pipeline Agent"
description: "Tracks deals through stages, identifies stalled opportunities, and recommends actions to close."
enabled: true

model:
  provider: anthropic
  model: "claude-sonnet-4-20250514"
  temperature: 0.4
  max_tokens: 8192
  context_window: 128000

tools:
  - search_knowledge
  - save_insight

browser_enabled: false

human_gates:
  enabled: true
  gate_before:
    - human_review

schedule:
  trigger: scheduled
  cron: "0 7 * * *"     # Daily at 7 AM

system_prompt_path: ""

max_consecutive_errors: 5
rag_write_confidence_threshold: 0.7

params:
  company_name: "Enclave Guard"
  stale_days: 7
  at_risk_days: 14
  forecast_months: 3
  min_deal_value_cents: 0
