agent_id: cad_advisor_v1
agent_type: cad_advisor
name: "CAD Advisor Agent"
description: "Advises architects on design-for-manufacturing optimization"
version: "1.0.0"

trigger:
  type: event
  events:
    - consultation_requested
    - design_review_requested

model_routing:
  primary: claude-sonnet-4-5-20250514
  analysis: claude-sonnet-4-5-20250514

human_gates:
  enabled: true
  gate_before:
    - human_review

rag_write_confidence_threshold: 0.75

params:
  consultation_duration_minutes: 60
  architecture_focus: true
  dfm_rules_enabled: true
