agent_id: mesh_repair_v1
agent_type: mesh_repair
name: "Mesh Repair Agent"
description: "Auto-repairs mesh issues, orients parts, and adds support structures"
version: "1.0.0"

trigger:
  type: event
  events:
    - file_analysis_completed
    - mesh_repair_requested

model_routing:
  primary: claude-sonnet-4-5-20250514
  analysis: claude-haiku-4-5-20250514

human_gates:
  enabled: true
  gate_before:
    - human_review

rag_write_confidence_threshold: 0.7

params:
  auto_repair: true
  max_repair_iterations: 5
  target_manifold: true
  target_watertight: true
